package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrAppResource;
import com.fth.rbac.server.core.entity.FrAppResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrAppResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    long countByExample(FrAppResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int deleteByExample(FrAppResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int insert(FrAppResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int insertSelective(FrAppResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    List<FrAppResource> selectByExample(FrAppResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    FrAppResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrAppResource record, @Param("example") FrAppResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByExample(@Param("record") FrAppResource record, @Param("example") FrAppResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByPrimaryKeySelective(FrAppResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByPrimaryKey(FrAppResource record);
}