package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrApp;
import com.fth.rbac.server.core.entity.FrAppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    long countByExample(FrAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByExample(FrAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByPrimaryKey(String appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insert(FrApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insertSelective(FrApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    List<FrApp> selectByExample(FrAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    FrApp selectByPrimaryKey(String appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrApp record, @Param("example") FrAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExample(@Param("record") FrApp record, @Param("example") FrAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKeySelective(FrApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKey(FrApp record);
}