package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrAppDeveloper;
import com.fth.rbac.server.core.entity.FrAppDeveloperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrAppDeveloperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    long countByExample(FrAppDeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByExample(FrAppDeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insert(FrAppDeveloper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insertSelective(FrAppDeveloper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    List<FrAppDeveloper> selectByExample(FrAppDeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    FrAppDeveloper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrAppDeveloper record, @Param("example") FrAppDeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExample(@Param("record") FrAppDeveloper record, @Param("example") FrAppDeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKeySelective(FrAppDeveloper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKey(FrAppDeveloper record);
}