package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrAppEnv;
import com.fth.rbac.server.core.entity.FrAppEnvExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FrAppEnvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    long countByExample(FrAppEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    int deleteByExample(FrAppEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    int insert(FrAppEnv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    int insertSelective(FrAppEnv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    List<FrAppEnv> selectByExample(FrAppEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrAppEnv record, @Param("example") FrAppEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    int updateByExample(@Param("record") FrAppEnv record, @Param("example") FrAppEnvExample example);
}