package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrAppRoleResource;
import com.fth.rbac.server.core.entity.FrAppRoleResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrAppRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    long countByExample(FrAppRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int deleteByExample(FrAppRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int insert(FrAppRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int insertSelective(FrAppRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    List<FrAppRoleResource> selectByExample(FrAppRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    FrAppRoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrAppRoleResource record, @Param("example") FrAppRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByExample(@Param("record") FrAppRoleResource record, @Param("example") FrAppRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByPrimaryKeySelective(FrAppRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByPrimaryKey(FrAppRoleResource record);
}