package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrEnv;
import com.fth.rbac.server.core.entity.FrEnvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrEnvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_env
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    long countByExample(FrEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_env
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByExample(FrEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_env
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insert(FrEnv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_env
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insertSelective(FrEnv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_env
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    List<FrEnv> selectByExample(FrEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_env
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrEnv record, @Param("example") FrEnvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_env
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExample(@Param("record") FrEnv record, @Param("example") FrEnvExample example);
}