package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrResource;
import com.fth.rbac.server.core.entity.FrResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    long countByExample(FrResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByExample(FrResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insert(FrResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insertSelective(FrResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    List<FrResource> selectByExample(FrResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    FrResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrResource record, @Param("example") FrResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExample(@Param("record") FrResource record, @Param("example") FrResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKeySelective(FrResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKey(FrResource record);
}