package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrRoleResource;
import com.fth.rbac.server.core.entity.FrRoleResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    long countByExample(FrRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByExample(FrRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insert(FrRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insertSelective(FrRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    List<FrRoleResource> selectByExample(FrRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    FrRoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrRoleResource record, @Param("example") FrRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExample(@Param("record") FrRoleResource record, @Param("example") FrRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKeySelective(FrRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByPrimaryKey(FrRoleResource record);
}