package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrRole;
import com.fth.rbac.server.core.entity.FrRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    long countByExample(FrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int deleteByExample(FrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insert(FrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int insertSelective(FrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    List<FrRole> selectByExample(FrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrRole record, @Param("example") FrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    int updateByExample(@Param("record") FrRole record, @Param("example") FrRoleExample example);
}