package com.fth.rbac.server.core.mapper;

import com.fth.rbac.server.core.entity.FrSysUser;
import com.fth.rbac.server.core.entity.FrSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FrSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    long countByExample(FrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int deleteByExample(FrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int insert(FrSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int insertSelective(FrSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    List<FrSysUser> selectByExample(FrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    FrSysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") FrSysUser record, @Param("example") FrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByExample(@Param("record") FrSysUser record, @Param("example") FrSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByPrimaryKeySelective(FrSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_sys_user
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    int updateByPrimaryKey(FrSysUser record);
}