package com.fth.rbac.server.core.entity;

import java.util.Date;

public class FrAppApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.app_id
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.app_name
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.status
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.creator
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.created_at
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_application
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public FrAppApplication(String appId, String appName, Integer status, Integer creator, Date createdAt) {
        this.appId = appId;
        this.appName = appName;
        this.status = status;
        this.creator = creator;
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_application
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public FrAppApplication() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.app_id
     *
     * @return the value of fr_app_application.app_id
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.app_id
     *
     * @param appId the value for fr_app_application.app_id
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.app_name
     *
     * @return the value of fr_app_application.app_name
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.app_name
     *
     * @param appName the value for fr_app_application.app_name
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.status
     *
     * @return the value of fr_app_application.status
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.status
     *
     * @param status the value for fr_app_application.status
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.creator
     *
     * @return the value of fr_app_application.creator
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.creator
     *
     * @param creator the value for fr_app_application.creator
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.created_at
     *
     * @return the value of fr_app_application.created_at
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.created_at
     *
     * @param createdAt the value for fr_app_application.created_at
     *
     * @mbg.generated Mon Nov 30 19:58:11 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}