package com.fth.rbac.server.core.entity;

import java.util.Date;

public class FrAppApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.id
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.name
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.creator
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_application.created_at
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_application
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public FrAppApplication(Integer id, String name, Integer creator, Date createdAt) {
        this.id = id;
        this.name = name;
        this.creator = creator;
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_application
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public FrAppApplication() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.id
     *
     * @return the value of fr_app_application.id
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.id
     *
     * @param id the value for fr_app_application.id
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.name
     *
     * @return the value of fr_app_application.name
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.name
     *
     * @param name the value for fr_app_application.name
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.creator
     *
     * @return the value of fr_app_application.creator
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.creator
     *
     * @param creator the value for fr_app_application.creator
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_application.created_at
     *
     * @return the value of fr_app_application.created_at
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_application.created_at
     *
     * @param createdAt the value for fr_app_application.created_at
     *
     * @mbg.generated Sat Nov 14 14:01:54 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}