package com.fth.rbac.server.core.entity;

import java.util.Date;

public class FrAppDeveloper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_developer.id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_developer.app_id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_developer.user_id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_developer.creator
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_developer.created_at
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public FrAppDeveloper(Integer id, String appId, Integer userId, Integer creator, Date createdAt) {
        this.id = id;
        this.appId = appId;
        this.userId = userId;
        this.creator = creator;
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_developer
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public FrAppDeveloper() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_developer.id
     *
     * @return the value of fr_app_developer.id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_developer.id
     *
     * @param id the value for fr_app_developer.id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_developer.app_id
     *
     * @return the value of fr_app_developer.app_id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_developer.app_id
     *
     * @param appId the value for fr_app_developer.app_id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_developer.user_id
     *
     * @return the value of fr_app_developer.user_id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_developer.user_id
     *
     * @param userId the value for fr_app_developer.user_id
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_developer.creator
     *
     * @return the value of fr_app_developer.creator
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_developer.creator
     *
     * @param creator the value for fr_app_developer.creator
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_developer.created_at
     *
     * @return the value of fr_app_developer.created_at
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_developer.created_at
     *
     * @param createdAt the value for fr_app_developer.created_at
     *
     * @mbg.generated Thu Dec 03 18:29:49 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}