package com.fth.rbac.server.core.entity;

public class FrAppRoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role_resource.id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role_resource.role_id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role_resource.resource_id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public FrAppRoleResource(Integer id, String roleId, String resourceId) {
        this.id = id;
        this.roleId = roleId;
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role_resource
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public FrAppRoleResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role_resource.id
     *
     * @return the value of fr_app_role_resource.id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role_resource.id
     *
     * @param id the value for fr_app_role_resource.id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role_resource.role_id
     *
     * @return the value of fr_app_role_resource.role_id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role_resource.role_id
     *
     * @param roleId the value for fr_app_role_resource.role_id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role_resource.resource_id
     *
     * @return the value of fr_app_role_resource.resource_id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role_resource.resource_id
     *
     * @param resourceId the value for fr_app_role_resource.resource_id
     *
     * @mbg.generated Tue Dec 01 23:06:48 CST 2020
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }
}