package com.fth.rbac.server.core.entity;

import java.util.Date;

public class FrAppRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.role_name
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.app_id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.parent_id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.id_path
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private String idPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.name_path
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private String namePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.creator
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_role.created_at
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public FrAppRole(String id, String roleName, String appId, String parentId, String idPath, String namePath, Integer creator, Date createdAt) {
        this.id = id;
        this.roleName = roleName;
        this.appId = appId;
        this.parentId = parentId;
        this.idPath = idPath;
        this.namePath = namePath;
        this.creator = creator;
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_role
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public FrAppRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.id
     *
     * @return the value of fr_app_role.id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.id
     *
     * @param id the value for fr_app_role.id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.role_name
     *
     * @return the value of fr_app_role.role_name
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.role_name
     *
     * @param roleName the value for fr_app_role.role_name
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.app_id
     *
     * @return the value of fr_app_role.app_id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.app_id
     *
     * @param appId the value for fr_app_role.app_id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.parent_id
     *
     * @return the value of fr_app_role.parent_id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.parent_id
     *
     * @param parentId the value for fr_app_role.parent_id
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.id_path
     *
     * @return the value of fr_app_role.id_path
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public String getIdPath() {
        return idPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.id_path
     *
     * @param idPath the value for fr_app_role.id_path
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setIdPath(String idPath) {
        this.idPath = idPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.name_path
     *
     * @return the value of fr_app_role.name_path
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public String getNamePath() {
        return namePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.name_path
     *
     * @param namePath the value for fr_app_role.name_path
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setNamePath(String namePath) {
        this.namePath = namePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.creator
     *
     * @return the value of fr_app_role.creator
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.creator
     *
     * @param creator the value for fr_app_role.creator
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_role.created_at
     *
     * @return the value of fr_app_role.created_at
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_role.created_at
     *
     * @param createdAt the value for fr_app_role.created_at
     *
     * @mbg.generated Tue Dec 01 23:18:56 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}