package com.fth.rbac.server.core.entity;

import java.util.Date;

public class FrAppEnv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_env.env_id
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    private String envId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_env.env_name
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    private String envName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_env.app_id
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_env.creator
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_app_env.created_at
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public FrAppEnv(String envId, String envName, String appId, Integer creator, Date createdAt) {
        this.envId = envId;
        this.envName = envName;
        this.appId = appId;
        this.creator = creator;
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_app_env
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public FrAppEnv() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_env.env_id
     *
     * @return the value of fr_app_env.env_id
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public String getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_env.env_id
     *
     * @param envId the value for fr_app_env.env_id
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public void setEnvId(String envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_env.env_name
     *
     * @return the value of fr_app_env.env_name
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_env.env_name
     *
     * @param envName the value for fr_app_env.env_name
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public void setEnvName(String envName) {
        this.envName = envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_env.app_id
     *
     * @return the value of fr_app_env.app_id
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_env.app_id
     *
     * @param appId the value for fr_app_env.app_id
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_env.creator
     *
     * @return the value of fr_app_env.creator
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_env.creator
     *
     * @param creator the value for fr_app_env.creator
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_app_env.created_at
     *
     * @return the value of fr_app_env.created_at
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_app_env.created_at
     *
     * @param createdAt the value for fr_app_env.created_at
     *
     * @mbg.generated Mon Nov 30 20:04:13 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}