package com.fth.rbac.server.core.entity;

import java.util.Date;

public class FrUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.id
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.username
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.nickname
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.phone
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.password
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.admin
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private Integer admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.status
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fr_user.created_at
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public FrUser(Integer id, String username, String nickname, String phone, String password, Integer admin, Integer status, Date createdAt) {
        this.id = id;
        this.username = username;
        this.nickname = nickname;
        this.phone = phone;
        this.password = password;
        this.admin = admin;
        this.status = status;
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public FrUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.id
     *
     * @return the value of fr_user.id
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.id
     *
     * @param id the value for fr_user.id
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.username
     *
     * @return the value of fr_user.username
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.username
     *
     * @param username the value for fr_user.username
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.nickname
     *
     * @return the value of fr_user.nickname
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.nickname
     *
     * @param nickname the value for fr_user.nickname
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.phone
     *
     * @return the value of fr_user.phone
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.phone
     *
     * @param phone the value for fr_user.phone
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.password
     *
     * @return the value of fr_user.password
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.password
     *
     * @param password the value for fr_user.password
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.admin
     *
     * @return the value of fr_user.admin
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public Integer getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.admin
     *
     * @param admin the value for fr_user.admin
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.status
     *
     * @return the value of fr_user.status
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.status
     *
     * @param status the value for fr_user.status
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fr_user.created_at
     *
     * @return the value of fr_user.created_at
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fr_user.created_at
     *
     * @param createdAt the value for fr_user.created_at
     *
     * @mbg.generated Fri Dec 04 14:02:25 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}